In [49]:
import numpy as np
import pandas as pd
from scipy import stats
import category_encoders as ce

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [50]:
data = pd.read_csv('/home/hasan/Desktop/DATA_SET/gender-height-weight-index.csv')

In [51]:
data.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [52]:
data.shape

(500, 4)

In [53]:
ce_ohe = ce.OneHotEncoder()
data = ce_ohe.fit_transform(data)
data.head()

Gender_1  Gender_2  Height  Weight  Index
0         1         0     174      96      4
1         1         0     189      87      2
2         0         1     185     110      4
3         0         1     195     104      3
4         1         0     149      61      3

# Finding Z-Score

In [54]:
z_score = np.abs(stats.zscore(data))
z_score

array([[1.02020406, 1.02020406, 0.24793878, 0.30911702, 0.18615685],
       [1.02020406, 1.02020406, 1.16487212, 0.58732233, 1.29127847],
       [0.98019606, 0.98019606, 0.92035656, 0.12364681, 0.18615685],
       ...,
       [0.98019606, 0.98019606, 1.76931458, 0.92735105, 0.92487451],
       [1.02020406, 1.02020406, 1.21915457, 0.34002872, 0.92487451],
       [1.02020406, 1.02020406, 0.18680989, 0.77279254, 0.92487451]])

In [55]:
threshold = 2.5
z_score_greater_than_threshild = np.where(z_score>threshold)
z_score_greater_than_threshild

(array([ 60,  62,  79,  85,  99, 150, 214, 224, 244, 273, 354, 453, 492]),
 array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]))

First array of row index and Second array for column index. Normally we take threshold=3 but 
I provide here threshold=2.5 

In [56]:
#printing one z-score where row index is 63 and column index is 4
print(z_score[62][4])

2.768713794904124


In [57]:
#removing outlier
data = data[(z_score<threshold).all(axis=1)]
data.head()

Gender_1  Gender_2  Height  Weight  Index
0         1         0     174      96      4
1         1         0     189      87      2
2         0         1     185     110      4
3         0         1     195     104      3
4         1         0     149      61      3

In [58]:
data.shape

(487, 5)

Here I am seeing some row dropped which rows had outlier